name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 * * *" # See https://crontab.guru/#0_7,9,11,17,20_*_*_*

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          set -o pipefail
          git config --global --add safe.directory /github/workspace
          git config --local user.email "clickgp99@gmail.com"
          git config --local user.name "yuurahz"
          git config --global --add safe.directory /github/workspace
          git add -A
          
          arr[0]="Updated"
          arr[1]="Commit"
          arr[2]="Fixed"
          arr[3]="Push"
          arr[4]="Penghijauan"
          arr[5]="Reboisasi"
          arr[6]="Pull"
          arr[7]="Push commit"
          arr[8]="Fix"
          arr[9]="Ngepush"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
